apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  namespace: daniel
  labels:
    app: spring-boot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-deployment
  template:
    metadata:
      name: spring-boot-deployment
      labels:
        app: spring-boot-deployment
    spec:
      containers:
        - name: spring-boot-deployment
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      